export function getBotCandidates(me = {}) {
  const pref = me.matchPreference || "이성+봇";
  const wantsFemale = pref.includes("이성") || pref.includes("모두") ? me.gender !== "여성" : pref.includes("동성") && me.gender === "여성";
  const wantsMale = pref.includes("이성") || pref.includes("모두") ? me.gender !== "남성" : pref.includes("동성") && me.gender === "남성";
  const all = [
    {
      id: "bot_best_001",
      isBot: true,
      nickname: "서연",
      gender: "여성",
      badge: "AI추천 인연",
      photo: "https://picsum.photos/seed/seoyeon/160/160",
      birthDate: "1994-10-08",
      birthHour: "오시 11~13",
      birthCode: "SAJU_BEST_01",
      ageBand: "30대",
      mbti: "ENFP",
      zodiac: "천칭자리",
      drinking: "가끔",
      smoking: "비흡연",
      exercise: "주 1~2회",
      education: "대학교",
      job: "마케팅",
      incomeRange: "5천~7천",
      height: "164",
      bodyStyle: "스타일 좋음",
      regionName: "서울 서초구",
      distanceKm: 2.1,
      tier: "최고궁합 봇"
    },
    {
      id: "bot_good_001",
      isBot: true,
      nickname: "지민",
      gender: "여성",
      badge: "AI추천 인연",
      photo: "https://picsum.photos/seed/jimin/160/160",
      birthDate: "1997-02-03",
      birthHour: "미시 13~15",
      birthCode: "SAJU_GOOD_01",
      ageBand: "20대",
      mbti: "INFJ",
      zodiac: "물병자리",
      drinking: "안 마심",
      smoking: "비흡연",
      exercise: "주 3~4회",
      education: "대학교",
      job: "디자이너",
      incomeRange: "3천~5천",
      height: "162",
      bodyStyle: "슬림",
      regionName: "서울 강남구",
      distanceKm: 4.8,
      tier: "좋은궁합 봇"
    },
    {
      id: "bot_normal_001",
      isBot: true,
      nickname: "민아",
      gender: "여성",
      badge: "AI추천 인연",
      photo: "https://picsum.photos/seed/mina/160/160",
      birthDate: "1991-06-12",
      birthHour: "축시 01~03",
      birthCode: "SAJU_NORMAL_01",
      ageBand: "30대",
      mbti: "ISFJ",
      zodiac: "쌍둥이자리",
      drinking: "보통",
      smoking: "비흡연",
      exercise: "거의 안함",
      education: "전문대",
      job: "사무직",
      incomeRange: "3천~5천",
      height: "166",
      bodyStyle: "보통",
      regionName: "경기 성남시",
      distanceKm: 13.5,
      tier: "보통궁합 봇"
    },
    {
      id: "bot_bad_001",
      isBot: true,
      nickname: "하린",
      gender: "여성",
      badge: "AI추천 인연",
      photo: "https://picsum.photos/seed/harin/160/160",
      birthDate: "1989-11-16",
      birthHour: "해시 21~23",
      birthCode: "SAJU_BAD_01",
      ageBand: "30대",
      mbti: "ESTJ",
      zodiac: "전갈자리",
      drinking: "즐김",
      smoking: "흡연",
      exercise: "매일",
      education: "대학원 이상",
      job: "전문직",
      incomeRange: "1억 이상",
      height: "168",
      bodyStyle: "탄탄",
      regionName: "서울 마포구",
      distanceKm: 11.2,
      tier: "최악궁합 봇"
    },
    {
      id: "bot_male_001",
      isBot: true,
      nickname: "도윤",
      gender: "남성",
      badge: "AI추천 인연",
      photo: "https://picsum.photos/seed/doyoon/160/160",
      birthDate: "1990-04-05",
      birthHour: "진시 07~09",
      birthCode: "SAJU_MALE_01",
      ageBand: "30대",
      mbti: "ENTJ",
      zodiac: "양자리",
      drinking: "가끔",
      smoking: "비흡연",
      exercise: "주 3~4회",
      education: "대학교",
      job: "개발자",
      incomeRange: "7천~1억",
      height: "180",
      bodyStyle: "탄탄",
      regionName: "서울 송파구",
      distanceKm: 8.6,
      tier: "좋은궁합 봇"
    }
  ];

  return all.filter(b => {
    if (!pref.includes("봇") && pref !== "모두 보기") return false;
    if (pref === "모두 보기") return true;
    if (b.gender === "여성") return wantsFemale;
    if (b.gender === "남성") return wantsMale;
    return true;
  });
}
